
server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      kafka:
        binder:
          brokers: 68.183.225.48:9092

    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


